# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ alpha ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install bundle
        run: |
          gem install bundler:2.2.16
          bundle config path vendor/bundle
          bundle update --bundler
          bundle install --jobs 4 --retry 3
          bundle update fastlane

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Configure Keystore
        run: |
          echo "$KEYSTORE" > ./keystore/keystore.b64
          base64 -d -i ./keystore/keystore.b64 > ./keystore/hipaduck_official.jks
          echo "storeFile=../keystore/hipaduck_official.jks" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          KEYSTORE: ${{ secrets.APP_KEYSTORE_BASE64 }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.APP_KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.APP_KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.APP_KEYSTORE_STORE_PASSWORD }}

      - name: Create Google Play Config file
        run: |
          echo "$PLAY_CONFIG_JSON" > google_play_config.json.b64
          base64 -d -i google_play_config.json.b64 > ./pc-api-7428597401125837512-667-71fd415b55dd.json 
        env:
          PLAY_CONFIG_JSON: ${{ secrets.GOOGLE_PLAY_ACCESS_API }}

      - name: Distribute app to Alpha track 🚀
        run: bundle exec fastlane deploy

      - name: Upload AAB to Artifact
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/bundle/release
